#配置项目名称、版本、版权年份
yc:
  name: YC
  version: 1.1.0
  copyrightYear: 2018
  profile: D:/profile/

#开发环境配置
server:
  #访问端口
  port: 81
  servlet:
    context-path: /yc
  tomcat:
    uri-encoding: utf-8

#日志配置
logging:
  level:
    com.billyang: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
    
#spring配置
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  devtools: 
    restart: 
      enabled: true 
#MyBatis配置
myBatis:
  #搜索指定包别名
  typeAliasesPackage: com.billyang.project
  #配置mapper的扫描，找到所有的mapper.xml配置文件
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEbabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10